CREATE TABLE LICENSE_BLACKLIST (
  LICENSE_ID CHAR(36) NOT NULL
)
<<>>
CREATE INDEX LICENSE_BLACKLIST_INDEX ON LICENSE_BLACKLIST (LICENSE_ID)
<<>>
CREATE TABLE LICENSE_NETCHECK_LOG (
  DATE_TIME         TIMESTAMP   NOT NULL,
  REMOTE_IP         VARCHAR(47) NOT NULL,
  LICENSE_ID        CHAR(36)    NOT NULL,
  EVENT_DESCRIPTION VARCHAR(35) NOT NULL
)
<<>>
CREATE INDEX LICENSE_NETCHECK_LOG_LICENSE_ID_INDEX ON LICENSE_NETCHECK_LOG (LICENSE_ID)
<<>>
CREATE INDEX LICENSE_NETCHECK_LOG_EVENT_DESCRIPTION_INDEX ON LICENSE_NETCHECK_LOG (EVENT_DESCRIPTION)
<<>>
CREATE TABLE LICENSE_NETCHECK_DESCRIPTION (
  LICENSE_ID          CHAR(36)          NOT NULL PRIMARY KEY,
  PRODUCT             VARCHAR(30)       NOT NULL,
  HOLDER              VARCHAR(100)      NOT NULL,
  EMAIL               VARCHAR(254),
  COMPANY             VARCHAR(100),
  DURATION_IN_DAYS    BIGINT            DEFAULT 365 NOT NULL CHECK (DURATION_IN_DAYS > 1),
  INSTALL_BEFORE_DATE TIMESTAMP, 
  LICENSE_TYPE        VARCHAR(30)       NOT NULL,
  MAX_ACTIVE          BIGINT  DEFAULT 2 NOT NULL CHECK (MAX_ACTIVE >= 1)
)
<<>>
CREATE INDEX LICENSE_NETCHECK_DESCRIPTION_HOLDER_INDEX ON LICENSE_NETCHECK_DESCRIPTION (HOLDER)
<<>>
CREATE INDEX LICENSE_NETCHECK_DESCRIPTION_EMAIL_INDEX ON LICENSE_NETCHECK_DESCRIPTION (EMAIL)
<<>>
CREATE INDEX LICENSE_NETCHECK_DESCRIPTION_COMPANY_INDEX ON LICENSE_NETCHECK_DESCRIPTION (COMPANY)
<<>>
CREATE TABLE LICENSE_NETCHECK_COUNTS (
  LICENSE_ID      CHAR(36)         NOT NULL PRIMARY KEY,
  INSTALL_COUNT   BIGINT DEFAULT 0 NOT NULL CHECK (INSTALL_COUNT >= 0),
  RENEWAL_COUNT   BIGINT DEFAULT 0 NOT NULL CHECK (RENEWAL_COUNT >= 0),
  REMOVAL_COUNT   BIGINT DEFAULT 0 NOT NULL CHECK (REMOVAL_COUNT >= 0),
  BLACKLIST_COUNT BIGINT DEFAULT 0 NOT NULL CHECK (BLACKLIST_COUNT >= 0),
  TOO_MANY_COUNT  BIGINT DEFAULT 0 NOT NULL CHECK (TOO_MANY_COUNT >= 0)
)
<<>>
CREATE TABLE LICENSE_WEB_REQUEST (
  LICENSE_ID   CHAR(36)       NOT NULL PRIMARY KEY,
  DATE_TIME    TIMESTAMP      NOT NULL,
  EMAIL        VARCHAR(254)   NOT NULL,
  NAME         VARCHAR(100)   NOT NULL,
  COMPANY      VARCHAR(100),
  REQUEST_TYPE VARCHAR(30)    NOT NULL,
  IGNORE_TRIAL BOOLEAN        DEFAULT FALSE NOT NULL,
  NO_EMAIL     BOOLEAN        DEFAULT FALSE NOT NULL
)
<<>>
CREATE INDEX LICENSE_WEB_REQUEST_REQUEST_TYPE_INDEX ON LICENSE_WEB_REQUEST (REQUEST_TYPE)
<<>>
CREATE INDEX LICENSE_WEB_REQUEST_DATE_TIME_INDEX ON LICENSE_WEB_REQUEST (DATE_TIME)
<<>>
CREATE INDEX LICENSE_WEB_REQUEST_EMAIL_INDEX ON LICENSE_WEB_REQUEST (EMAIL)
<<>>
CREATE INDEX LICENSE_WEB_REQUEST_NAME_INDEX ON LICENSE_WEB_REQUEST (NAME)
<<>>
CREATE INDEX LICENSE_WEB_REQUEST_COMPANY_INDEX ON LICENSE_WEB_REQUEST (COMPANY)
<<>>
